name: Build and Release

on:
  push:
    tags:
      - "v*.*.*" # Dispara quando um tag de versão é criada

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependências
        run: pnpm install --frozen-lockfile

      - name: Rodar build
        run: pnpm build

      - name: Compactar pasta dist
        run: zip -r dist.zip dist/

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
