name: Build and Release

on:
  workflow_run:
    workflows: ["Create Tag"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Zip
        run: zip -r dist.zip dist/

      - name: Obter a última tag
        id: get_tag
        run: echo "TAG=$(git describe --tags --match 'v*' --abbrev=0)" >> $GITHUB_ENV

      - name: Verificar tag encontrada
        run: echo "echo ${{ env.ref_name }}"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: dist.zip
