name: Create Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Ler versão do package.json
        id: package
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Criar tag se não existir
        run: |
          if ! git rev-parse "v${VERSION}" >/dev/null 2>&1; then
            git tag "v${VERSION}"
            git push origin "v${VERSION}"
          else
            echo "Tag v${VERSION} já existe, pulando..."
          fi

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 10
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Zip
        run: zip -r dist.zip dist/

      - name: GitHub Tag Name example
        run: |
            echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
            echo "Tag name from github.ref_name: ${{  env.VERSION }}"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: ${{ env.VERSION }}
            files: dist.zip
