name: Create Tag

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Ler versão do package.json
        id: package
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
            version: 10
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Zip
        run: zip -r dist.zip dist/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: v${{ env.VERSION }}
            files: dist.zip
